version: '3.4'

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    hostname: mysql_db
    networks:
      - common
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=fynd123
      - MYSQL_DATABASE=fynd_practice
      - MYSQL_USER=fynd_acad
      - MYSQL_PASSWORD=fynd123
    ports:
      - "3305:3306"
    volumes:
      - /home/nitin/fynd_acad/docker-data:/var/lib/mysql 

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - host=mysql_db
      - port=3306
      - mysql_host=mysql_db
      - mysql_port=3306
      - mysql_user=fynd_acad
      - mysql_password=fynd123
      - mysql_database=fynd_acad
    networks:
      - common
    tty: true
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"


networks:
  common:
    # Use a custom driver
    driver: bridge